version: '3.8'

services:
  app:
    build: .
    container_name: finqna_app
    depends_on:
      elasticsearch:
        condition: service_healthy
      db:
        condition: service_started
    ports:
      - "8501:8501"
    env_file:
      - .envrc
    # volumes:
    #   - .:/app

  db:
    image: postgres:16
    container_name: finqna_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:8.4.3
    container_name: finqna_elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  pgdata:
  esdata: